// Pure resolution: observations plus validated producer-curated expectations.
// Regional inputs never become evidence that someone observed a species here.

import type { FieldTruth } from "@/lib/outside/pointmoon";
import type {
  PointmoonPhenophase,
  PointmoonPhotoAsset,
  PointmoonSpeciesRecency,
} from "@/lib/outside/pointmoon-contract";
import type { PhenologyEntry } from "@/lib/outside/types";
import { hasTaxa, matchesTopic } from "@/lib/outside/observations";
import type { TopicTag } from "@/schema/pack";
import { castSlug, observedLine } from "./member";
import { isYoungestAbility, isYoungestYearGroup, safetyFor } from "./safety";
import { collapseByTaxon, TaxonKeyring, type TaxonMatch } from "./taxon-identity";

/** How a member earned its place, and therefore what may be claimed of it. */
export type HonestyTier = "recorded" | "regional";

/** One resolved cast member, ready to store. Mirrors the CastMember model. */
export interface ResolvedCastMember {
  commonName: string;
  scientificName: string | null;
  photoUrl: string | null;
  photoCreator: string | null;
  photoRole: "observation" | "taxon-reference" | null;
  photoAttribution: string | null;
  /**
   * The licence the photograph arrived under, RECORDED RATHER THAN JUDGED.
   *
   * Was `"cc0" | "cc-by" | null`, which quietly nulled every other licence.
   * That was harmless only while the reads upstream refused to fetch anything
   * else; now that they accept the whole open set (#341), narrowing here would
   * strip `cc-by-nc` and `cc-by-sa` down to null and the credit line would
   * print "licence not stated" over an image whose licence is stated and
   * carries real conditions. The licence has to travel with the image, so it
   * is carried as it came.
   */
  photoLicense: string | null;
  photoSourceUrl: string | null;
  photoObservationId: string | null;
  /**
   * Every picture Pointmoon held of this species at resolve time, best claim
   * first, with the seven flat fields above as element zero (#984).
   *
   * ABSENT, NEVER EMPTY, and absent is the ordinary case: only the recorded
   * path has a gallery to carry. A historical or phenology-reference member
   * has one reference photograph and says so by not having this key, which is
   * the same discipline `recency` and `phenophase` already run on.
   */
  photos?: PointmoonPhotoAsset[];
  iconicTaxon: string | null;
  honestyTier: HonestyTier;
  lastSeenWindow: number | null;
  yearsObserved: number | null;
  historicalAvgCount: number | null;
  safetyNote: string | null;
  sortRank: number;
  absent: boolean;
  /**
   * The observed leg (#959), carried as the tokens Pointmoon sent and only on
   * a recorded, present member — the historical and phenology tiers have no
   * field for it, and an absence has no sighting to be fresh. Optional rather
   * than null so every fixture and caller that predates it still compiles
   * and resolves an identical cast.
   */
  recency?: PointmoonSpeciesRecency;
  phenophase?: PointmoonPhenophase;
  /**
   * The observed line, composed HERE at resolve time from the tokens and one
   * clock, so a client-rendered tile shows the same words the server sent:
   * a fresh `new Date()` on hydration could turn "seen today" into "seen
   * yesterday" across UTC midnight (Codex review on PR #960, round five).
   */
  observed?: string | null;
}

export interface ResolvedCast {
  /** The cast the finding surfaces show, in findability order. */
  members: ResolvedCastMember[];
  /** Striking absences, carried for the closing line. Never shown as findable. */
  absences: ResolvedCastMember[];
}

/**
 * Scientific name (lowercased) to what iNaturalist says the species is and
 * looks like. Generated by `scripts/build-taxon-reference.mjs`; see
 * `lib/outside/taxon-reference.ts`. Declared structurally rather than imported
 * so this file keeps no dependency on a module that reads the disk.
 */
export type TaxonReferenceIndex = Record<
  string,
  { iconicTaxon: string | null; photo?: PointmoonPhotoAsset }
>;

/** One producer-ranked historical observation used as regional evidence. */
export interface HistoricalMember {
  name: string;
  scientificName: string | null;
  iconicTaxon: string | null;
  /**
   * Typed as the producer's own asset rather than re-declared narrowly: the
   * licence union widens as the contract does, and a structural copy that
   * pinned it to two values made an ordinary assignment fail to compile while
   * describing the same data.
   */
  photo: PointmoonPhotoAsset | null;
}

export interface ResolveCastQuery {
  /** One Pointmoon read. Null (a failed read) resolves the regional cast alone. */
  data: FieldTruth | null;
  /** The clock the observed line is phrased against. Defaults to now. */
  now?: Date;
  /**
   * Pointmoon's producer-ranked, multi-year observations for this location and
   * seasonal window. The typed phenology below is the fallback when this is
   * empty.
   */
  historical?: readonly HistoricalMember[];
  /** Validated producer-curated regional entries. Empty when the producer is silent. */
  phenology?: readonly PhenologyEntry[];
  /**
   * What each phenology species is and looks like. Absent resolves exactly as
   * this file always did, so every existing caller and every recorded fixture
   * gets an identical cast.
   */
  taxonReferences?: TaxonReferenceIndex;
  /**
   * A profile already opened from this cast. When the species is still in the
   * current evidence, consider it before the layout bound so the profile
   * cannot lose the member that linked to it. An unknown slug changes
   * nothing and therefore still resolves to a 404 at the route.
   */
  profileSlug?: string | null;
  /** The lesson subject, when taxonomy can express it. Ranked before the cap. */
  topic?: TopicTag | null;
  /**
   * STRICT TOPIC FILTER (nc#233), OFF BY DEFAULT.
   *
   * `topic` alone only ever RANKS: it moves a matching species ahead of the
   * cap, but an unrelated recurrent bird still fills the cast down to
   * `MIN_MEMBERS` when too little matches. That is the right answer for a
   * general surface — Today leads with the lesson's subject but is still
   * honestly a whole-neighbourhood read.
   *
   * A surface that claims "who THIS LESSON is about" — the in-lesson
   * speak-and-show, the door's evidence, the printed reference cards — makes a
   * narrower claim, and ranking cannot keep it: a minibeast lesson with only
   * two minibeasts recorded would still show four more birds and a pear tree
   * to reach six. Set this true and, when the topic is one taxonomy can
   * answer (`hasTaxa`), only members whose taxon matches ever enter the cast.
   * The `MIN_MEMBERS` backfill through recurrence, the historical tier and the
   * phenology file is skipped entirely rather than relaxed, so nothing
   * off-topic can ever reach the cap. Zero matches is a complete, honest
   * answer — an empty cast — never a mismatched one.
   *
   * A topic taxonomy cannot express (art, senses, weather, seasons) makes no
   * species claim at all, so this flag does nothing for it: those sessions
   * keep the ranked, general cast, exactly as `hasTaxa`'s own contract says
   * they should ("this topic was never about species").
   */
  topicFilter?: boolean;
  /** The class's year group; drives the youngest-years safety exclusion. */
  yearGroup?: string | null;
  /**
   * The class's ability band, from its LearnerContext (#205). When present it
   * DECIDES the youngest-years exclusion and the year group is not consulted —
   * age and ability are orthogonal (J2), and the exclusion is about who is
   * reading. Absent, the year group answers exactly as it always has, so every
   * class that predates the column resolves an identical cast.
   */
  abilityBand?: string | null;
}

/** The cast's target size. Fewer is honest; more is noise a class cannot hold. */
const MIN_MEMBERS = 6;

/**
 * A LAYOUT BOUND, NOT A RELEVANCE ONE (#1030).
 *
 * Johan, 2026-09-07: "Up to four species? This is also a bug. We don't need to
 * limit, we need to make it contextual."
 *
 * `MAX_MEMBERS = 8` used to stand here, and `/cast` narrowed it again to four.
 * Both were a count doing relevance's job: the eighth slot went to whatever
 * ranked eighth, and a ninth genuinely relevant creature was dropped for being
 * ninth. Worse, the same organism arriving as several taxon versions spent
 * several of those slots before the cap was even reached, which is the defect
 * `./taxon-identity.ts` exists to remove.
 *
 * What remains is a bound on the PAGE, not on the lesson. Twelve is the depth
 * every deep surface already reads (`lib/cast/surface.ts`'s `CAST_DEPTH`), so
 * the board and the brief cannot disagree about which creatures exist, and it
 * is about as many faces as fit a screen a teacher holds up in front of a
 * class. Nothing between here and the page trims further: a context with two
 * creatures in it resolves to two, and one with eleven resolves to eleven.
 */
export const CAST_LAYOUT_MAX = 12;

/** How many absences are worth carrying. One line's worth, not a list. */
const MAX_ABSENCES = 3;
/** Multi-year recurrence: what earns an ordinary place. */
const RECURRENCE_YEARS = 2;

/**
 * The observation shape the recurrence fields live on. lib/outside/pointmoon.ts
 * types only the slice the old card read; the recurrence and absence fields are
 * present in every real payload (verified against four recorded cities) and are
 * read here. Every one is optional: a payload without them still resolves, it
 * simply resolves to less.
 */
interface RecurrenceEntry {
  name?: string;
  scientificName?: string;
  /**
   * Pointmoon's presence evidence. Read here for ONE field, `taxonId`: it is
   * the provider's own answer to "which taxon is this row", and therefore the
   * only handle that survives a row whose scientific name never arrived. See
   * `./taxon-identity.ts`.
   */
  presence?: { taxonId?: string | null } | null;
  count?: number;
  photoUrl?: string | null;
  photo?: PointmoonPhotoAsset | null;
  photos?: PointmoonPhotoAsset[];
  iconicTaxon?: string;
  historicalAvgCount?: number;
  yearsObserved?: number;
  ratioToHistorical?: number;
  presenceRate?: number;
  recency?: PointmoonSpeciesRecency;
  phenophase?: PointmoonPhenophase;
}

function observations(data: FieldTruth | null): {
  nearby: RecurrenceEntry[];
  absent: RecurrenceEntry[];
  windowDays: number | null;
} {
  const obs = (
    data?.facts?.fieldSnapshot as
      | {
          observations?: {
            nearby?: RecurrenceEntry[];
            birds?: { notable?: RecurrenceEntry[] };
            absent?: RecurrenceEntry[];
            recentWindowDays?: number;
          };
        }
      | undefined
  )?.observations;

  if (!obs) return { nearby: [], absent: [], windowDays: null };

  return {
    nearby: [...(obs.nearby ?? []), ...(obs.birds?.notable ?? [])],
    absent: obs.absent ?? [],
    windowDays: typeof obs.recentWindowDays === "number" ? obs.recentWindowDays : null,
  };
}

/**
 * Whether the current Pointmoon projection contains at least one present
 * observation a refreshed cast can be grounded in. Regional phenology is a
 * sound day-one fallback, but it is not evidence strong enough to replace a
 * class's existing, deliberately stable cast.
 */
export function hasRecentObservationEvidence(data: FieldTruth | null): boolean {
  return observations(data).nearby.length > 0;
}

/** A trimmed non-empty string, or null. Nothing nameless reaches a cast. */
function text(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0 ? value.trim() : null;
}

function wholeNumber(value: unknown): number | null {
  return typeof value === "number" && Number.isFinite(value) ? Math.round(value) : null;
}

/**
 * Findability score for a recorded species: how likely a child sent to look for
 * this actually finds it. Higher is more findable.
 *
 * ratioToHistorical is the species' current count against its own baseline, so
 * 1.0 is a normal year. Normal-or-above scores highest; well below its own
 * baseline scores lowest, because that is precisely a species that is here in
 * principle and hard to find in practice. A species with no ratio reported sits
 * in the middle: unknown is not the same as bad, and demoting it below a known
 * rarity would be reading absence of evidence as evidence.
 */
function findability(entry: RecurrenceEntry): number {
  const ratio = entry.ratioToHistorical;
  if (typeof ratio !== "number" || !Number.isFinite(ratio)) return 0.5;
  if (ratio >= 0.9) return 1;
  if (ratio >= 0.6) return 0.85;
  if (ratio >= 0.35) return 0.6;
  return 0.3;
}

/**
 * HOW RECENTLY SOMEONE SAW THIS, coarsely (#1030).
 *
 * The ticket's ranking is topic relevance, then recency, then photo quality.
 * Recency is bucketed rather than compared instant by instant, because a board
 * is not a leaderboard: two creatures both seen this week are equally worth
 * looking for, and letting six hours between them outrank everything else
 * would hand the ordering to whichever observer uploaded last.
 *
 * Unknown sits ABOVE stale and below fresh, on the same reasoning `findability`
 * gives for its own 0.5: a row Pointmoon did not sample is not a row that was
 * looked for and not found. Reading absence of evidence as evidence is the one
 * mistake this whole file is written to avoid.
 */
function recencyRank(entry: RecurrenceEntry, now: Date): number {
  const stamp = entry.recency?.latestObservedAt;
  if (typeof stamp !== "string") return 0.5;
  const seen = Date.parse(stamp);
  if (!Number.isFinite(seen)) return 0.5;
  const days = (now.getTime() - seen) / 86_400_000;
  if (days < 0) return 0.5;
  if (days <= 7) return 1;
  if (days <= 30) return 0.4;
  return 0.2;
}

/**
 * WHETHER A CHILD CAN SEE WHAT THEY ARE LOOKING FOR (#1030).
 *
 * A photograph someone took of this species near here is the strongest thing
 * the board can show; a reference portrait of the species is honest and
 * weaker; a drawn plate is a name without a face. Unlike recency, "none" here
 * is a known absence rather than an unasked question, so it ranks last.
 */
function photoRank(entry: RecurrenceEntry): number {
  const role = entry.photo?.role;
  if (role === "observation") return 1;
  if (role === "taxon-reference") return 0.5;
  return 0;
}

function toMember(
  entry: RecurrenceEntry,
  tier: HonestyTier,
  windowDays: number | null,
  absent: boolean,
  now: Date = new Date()
): ResolvedCastMember | null {
  const commonName = text(entry.name);
  if (!commonName) return null;
  const scientificName = text(entry.scientificName);
  const safety = safetyFor(scientificName);
  const photo = entry.photo ?? null;

  const member: ResolvedCastMember = {
    commonName,
    scientificName,
    // Only the complete nested asset is authoritative. The old bare URL is
    // deliberately ignored so it cannot become a releaseable stored image.
    photoUrl: text(photo?.url),
    photoCreator: text(photo?.creator),
    photoRole:
      photo?.role === "observation" || photo?.role === "taxon-reference"
        ? photo.role
        : null,
    photoAttribution: text(photo?.attribution),
    photoLicense: text(photo?.license),
    photoSourceUrl: text(photo?.sourceUrl),
    photoObservationId: text(photo?.observationId),
    iconicTaxon: text(entry.iconicTaxon),
    honestyTier: tier,
    // An absence has no sighting window: it is defined by not having been seen.
    lastSeenWindow: absent ? null : windowDays,
    yearsObserved: wholeNumber(entry.yearsObserved),
    historicalAvgCount: wholeNumber(entry.historicalAvgCount),
    safetyNote: safety?.note ?? null,
    sortRank: 0,
    absent,
  };
  // The gallery, carried whole (#984). Element zero is already the flat
  // fields above, so nothing here re-derives `photoUrl` from it — a payload
  // whose `photos[0]` disagreed with its `photo` is upstream's business, and
  // a consumer quietly picking a winner between them is how two fields start
  // meaning different things.
  if (entry.photos?.length) member.photos = entry.photos;
  // The observed leg rides only on a present sighting. The projection has
  // already validated both objects, so this is carriage, not a second gate.
  if (!absent && entry.recency) member.recency = entry.recency;
  if (!absent && entry.phenophase) member.phenophase = entry.phenophase;
  if (member.phenophase) member.observed = observedLine(member, now);
  return member;
}

/**
 * A historical observation as a regional member (#323, #359).
 *
 * Regional, not recorded, and deliberately so. Pointmoon sampled the same
 * seasonal window across prior years near this location. That is stronger
 * than a region-wide authored list and weaker than a sighting here this week,
 * so `lastSeenWindow` remains null.
 */
function historicalMember(entry: HistoricalMember): ResolvedCastMember | null {
  const commonName = text(entry.name);
  if (!commonName) return null;
  const scientificName = text(entry.scientificName);
  const safety = safetyFor(scientificName);
  const photo = entry.photo;

  return {
    commonName,
    scientificName,
    photoUrl: text(photo?.url),
    photoCreator: text(photo?.creator),
    photoRole:
      photo?.role === "observation" || photo?.role === "taxon-reference" ? photo.role : null,
    photoAttribution: text(photo?.attribution),
    photoLicense: text(photo?.license),
    photoSourceUrl: text(photo?.sourceUrl),
    photoObservationId: text(photo?.observationId),
    iconicTaxon: text(entry.iconicTaxon),
    honestyTier: "regional",
    lastSeenWindow: null,
    yearsObserved: null,
    historicalAvgCount: null,
    safetyNote: safety?.note ?? null,
    sortRank: 0,
    absent: false,
  };
}

/**
 * A phenology entry as a regional member: in season, not observed.
 *
 * ── THE TAXON REFERENCE, AND WHAT IT DOES NOT CHANGE (#321) ────────────────
 *
 * This used to return `iconicTaxon: null` and no photograph, with the comment
 * "the phenology files carry no photographs, a regional member shows its name
 * without a picture rather than borrowing one from somewhere else". The second
 * half of that was right and the first half was a fact about our reading rather
 * than about the world. iNaturalist holds thousands of releasable photographs
 * of these exact species, and the photo contract has carried a
 * `taxon-reference` role for them since it was written.
 *
 * The cost of not asking was visible: with no `iconicTaxon`, the drawn plate
 * picked its mark by taxon and therefore drew the SAME LEAF for a swallow, a
 * spider and a fire salamander.
 *
 * NOTHING HERE UPGRADES A CLAIM. The tier stays `regional`, so `castMaterial`
 * renders the picture inset in a paper frame rather than full-bleed, the
 * caption stays "usually around here now", and this member cannot reach the
 * seen group. `taxon-reference` says "this is what the species looks like",
 * which is a different sentence from "someone photographed this one here", and
 * the two are kept apart by the role that travels with the asset.
 *
 * The reference is passed in rather than read, so this file stays pure and a
 * recorded payload still replays to an identical cast.
 *
 * ── AN EVENT ROW HAS NO SPECIMEN TO REFER TO (#1020) ───────────────────────
 *
 * The paragraphs above are about a row that names a creature. A row marked
 * `kind: "event"` names something the season is doing — "Swallow Gathering",
 * "Starling Murmuration", "Red Deer Rut" — and the whole apparatus above is
 * wrong for it: the reference lookup returns a portrait of ONE barn swallow,
 * the iconic taxon says Aves, and the member that comes out is indexed,
 * ranked, topic-matched and printed as a specimen a child could be sent to
 * find. `matchesTopic` cannot catch it, because taxonomically Aves IS what a
 * birds lesson asked for; the row is simply not what it claims to be.
 *
 * So an event resolves with no taxon, no photograph and no scientific name:
 * exactly the member "Autumn Colour" and "Dawn Chorus" have always resolved
 * to, and for the same reason. It keeps its name, its note and its place in
 * the cast — a class is still told the swallows are massing — and it cannot
 * be mistaken for a thing standing outside the gate.
 *
 * The SAFETY note is read from the authored scientific name anyway, before
 * the identity is dropped. A gate that removes a specimen has no business
 * removing a warning about the animal involved, and the two are separate
 * questions. (No event row maps to a safety rule today; this is the shape
 * being right rather than a behaviour change.)
 */
export function resolvePhenologyReference(
  entry: Pick<PhenologyEntry, "species" | "scientificName" | "kind">,
  references: TaxonReferenceIndex
): ResolvedCastMember | null {
  const commonName = text(entry.species);
  if (!commonName) return null;
  const authoredScientificName = text(entry.scientificName);
  const safety = safetyFor(authoredScientificName);
  const isEvent = entry.kind === "event";
  // Absent for the entries that are not species at all: "Autumn Colour",
  // "Dawn Chorus", "First Frost", and every row authored `kind: "event"`.
  // They have no taxon and no photograph, and a drawn plate is the honest and
  // complete answer for them.
  const scientificName = isEvent ? null : authoredScientificName;
  const reference = scientificName ? references[scientificName.toLowerCase()] : undefined;
  const photo = reference?.photo ?? null;

  return {
    commonName,
    scientificName,
    photoUrl: text(photo?.url),
    photoCreator: text(photo?.creator),
    photoRole: photo?.role === "taxon-reference" ? photo.role : null,
    photoAttribution: text(photo?.attribution),
    photoLicense: text(photo?.license),
    photoSourceUrl: text(photo?.sourceUrl),
    photoObservationId: text(photo?.observationId),
    iconicTaxon: text(reference?.iconicTaxon),
    honestyTier: "regional",
    lastSeenWindow: null,
    yearsObserved: null,
    historicalAvgCount: null,
    safetyNote: safety?.note ?? null,
    sortRank: 0,
    absent: false,
  };
}

/**
 * ONE ROW PER ORGANISM, BEFORE ANYTHING IS RANKED (#1030).
 *
 * The versions of one creature are folded together here rather than filtered
 * out later, and the order matters. Ranking first would compare fragments of
 * one organism against whole ones — its count, its recurrence and its
 * freshness split three ways — and then spend three slots on the fragments
 * that survived. Collapsing first means every later step, the recurrence gate
 * included, sees one row carrying the best evidence any version had.
 *
 * WHICH VERSION SURVIVES: the more specific identification, then the longer
 * record, then the bigger count. WHAT IS CARRIED ACROSS: only a field the
 * survivor does not have, and only from a version that is the same NAME (the
 * `taxon-id` and `binomial` rules). Nothing is carried across a rank rollup or
 * a genus transfer: a photograph taken of "some Pieris" is not a photograph of
 * a small white, and attaching it would be the invention this product exists
 * not to make. No number is ever summed — a duplicate row is another reading
 * of the same sighting, not more of it.
 */
function collapseVersions(entries: readonly RecurrenceEntry[]): RecurrenceEntry[] {
  return collapseByTaxon<RecurrenceEntry>(entries, (entry) => entry, {
    prefer: (a, b) => {
      const years = (b.yearsObserved ?? 0) - (a.yearsObserved ?? 0);
      if (years !== 0) return years;
      return (b.count ?? 0) - (a.count ?? 0);
    },
    merge: (representative, duplicate, match) =>
      fillFromSameName(representative, duplicate, match),
  });
}

/** The fields a duplicate may fill in, and only when it names the same taxon. */
const CARRIED: ReadonlyArray<keyof RecurrenceEntry> = [
  "scientificName",
  "iconicTaxon",
  "photo",
  "photos",
  "presence",
  "recency",
  "phenophase",
  "count",
  "yearsObserved",
  "historicalAvgCount",
  "ratioToHistorical",
  "presenceRate",
];

function fillFromSameName(
  representative: RecurrenceEntry,
  duplicate: RecurrenceEntry,
  match: TaxonMatch
): RecurrenceEntry {
  if (match !== "taxon-id" && match !== "binomial") return representative;

  const filled: RecurrenceEntry = { ...representative };
  for (const key of CARRIED) {
    if (filled[key] === undefined || filled[key] === null) {
      const value = duplicate[key];
      if (value !== undefined && value !== null) {
        (filled as Record<string, unknown>)[key] = value;
      }
    }
  }
  return filled;
}

/** The same collapse for the historical tier, which carries no presence id. */
function collapseHistorical(entries: readonly HistoricalMember[]): HistoricalMember[] {
  return collapseByTaxon<HistoricalMember>(entries, (entry) => entry, {
    merge: (representative, duplicate, match) =>
      match === "taxon-id" || match === "binomial"
        ? { ...representative, photo: representative.photo ?? duplicate.photo }
        : representative,
  });
}

/**
 * Resolve a class's cast from one read plus this week's phenology.
 *
 * Deterministic: the same payload, phenology and year group always give the
 * same cast, which is what makes a recorded payload a replayable fixture.
 * Never throws — a malformed or absent payload resolves to the regional cast,
 * and an empty everything resolves to an empty cast rather than an invention.
 */
export function resolveCast(query: ResolveCastQuery): ResolvedCast {
  const {
    data,
    now = new Date(),
    historical = [],
    phenology = [],
    yearGroup,
    abilityBand,
    taxonReferences = {},
    topic = null,
  } = query;
  const raw = observations(data);
  const windowDays = raw.windowDays;
  // One row per organism before a single ranking comparison is made (#1030).
  const nearby = collapseVersions(raw.nearby);
  const absent = collapseVersions(raw.absent);
  // The band decides when there is one; otherwise the year group, unchanged.
  const excludeHazards =
    typeof abilityBand === "string" && abilityBand.trim().length > 0
      ? isYoungestAbility(abilityBand)
      : isYoungestYearGroup(yearGroup);

  // A species the youngest years should not be sent to find leaves the cast
  // entirely. For every other year group it stays, carrying its note.
  const admissible = (scientific: string | null): boolean => {
    if (!excludeHazards) return true;
    return safetyFor(scientific)?.handling !== "exclude-youngest";
  };

  // Recurrence splits the general cast: multi-year first, single-year reserve.
  const recurrent: Array<{ member: ResolvedCastMember; entry: RecurrenceEntry }> = [];
  const singleYear: Array<{ member: ResolvedCastMember; entry: RecurrenceEntry }> = [];

  for (const entry of nearby) {
    const member = toMember(entry, "recorded", windowDays, false, now);
    if (!member) continue;
    if (!admissible(member.scientificName)) continue;

    const years = member.yearsObserved ?? 0;
    if (years >= RECURRENCE_YEARS) recurrent.push({ member, entry });
    else singleYear.push({ member, entry });
  }

  /**
   * (3) THE ORDER (#167, extended by #1030).
   *
   * Topic relevance is not in this comparator because it is not a tie-break:
   * the `topicFirst` pass below takes every on-topic member ahead of this
   * ranking entirely, and `lib/cast/live.ts` re-anchors the same way for a
   * lesson's tags. What is left is the order among equally relevant creatures,
   * and #1030 sets it: recency, then photo quality, then the child-findability
   * chain #167 established.
   *
   * Findability stays underneath rather than being replaced. "Which of these
   * can a child actually find" is a different question from "which was seen
   * most recently", and on a payload where nobody's freshness was sampled —
   * the recorded Berkeley read is one — it is the only question there is an
   * answer to.
   */
  const byRank = (a: { entry: RecurrenceEntry }, b: { entry: RecurrenceEntry }): number => {
    const fresh = recencyRank(b.entry, now) - recencyRank(a.entry, now);
    if (fresh !== 0) return fresh;
    const pictured = photoRank(b.entry) - photoRank(a.entry);
    if (pictured !== 0) return pictured;
    const score = findability(b.entry) - findability(a.entry);
    if (score !== 0) return score;
    // A tie breaks toward the longer record, then the bigger presence.
    const years = (b.entry.yearsObserved ?? 0) - (a.entry.yearsObserved ?? 0);
    if (years !== 0) return years;
    return (b.entry.count ?? 0) - (a.entry.count ?? 0);
  };

  recurrent.sort(byRank);
  singleYear.sort(byRank);

  const historicalMembers = collapseHistorical(historical)
    .map(historicalMember)
    .filter((member): member is ResolvedCastMember =>
      Boolean(member && admissible(member.scientificName))
    );
  // THE AUTHORED NAME, NOT THE RESOLVED ONE (#1027).
  //
  // `resolvePhenologyReference` nulls `scientificName` for a `kind: "event"`
  // row on purpose — an event borrows no species' taxon, photograph or
  // identity. It reads the safety NOTE off the authored name first, before the
  // drop, because a gate that removes a specimen has no business removing a
  // warning. `admissible` is the second reader of that same verdict and it must
  // be told the same thing: asked about the nulled field, it would let an event
  // whose authored taxon is an `exclude-youngest` genus into a Reception cast
  // while still printing the warning — the worst of both answers. So the
  // exclusion is decided on what the row says it is about, and the identity
  // stays dropped. For a species row the two names are the same string.
  const phenologyMembers = phenology.flatMap((entry) => {
    const member = resolvePhenologyReference(entry, taxonReferences);
    if (!member) return [];
    const safetyName = member.scientificName ?? text(entry.scientificName);
    return admissible(safetyName) ? [member] : [];
  });

  const chosen: ResolvedCastMember[] = [];
  // The taxa already on the board. A keyring rather than a set of name
  // strings, so a species taken from the recorded tier cannot be taken again
  // from the phenology file under its subspecies or its genus (#1030).
  const seen = new TaxonKeyring();

  const take = (member: ResolvedCastMember): void => {
    if (chosen.length >= CAST_LAYOUT_MAX) return;
    if (!seen.claim({ name: member.commonName, scientificName: member.scientificName })) return;
    chosen.push(member);
  };

  // A profile is a read of an already-selected member, not a new generic cast
  // decision. The caller may have come from a lesson whose topic promoted a
  // species that a generic cast would place below its layout bound. Find
  // the requested member only among today's real inputs and take it first;
  // this preserves the evidence tier without turning the route into a global
  // encyclopaedia lookup.
  const profileSlug = query.profileSlug?.trim();
  if (profileSlug) {
    const profileMember = [
      ...recurrent.map(({ member }) => member),
      ...singleYear.map(({ member }) => member),
      ...historicalMembers,
      ...phenologyMembers,
    ].find((member) => castSlug(member) === profileSlug);
    if (profileMember) take(profileMember);
  }

  // A lesson topic must be considered before the layout bound. Otherwise
  // common recurrent birds can consume every slot before a relevant plant or
  // fungus is even considered. Taxonomy-free topics keep the original recipe.
  const topicMapped = topic !== null && hasTaxa(topic);
  if (topicMapped) {
    const topicFirst = (members: readonly ResolvedCastMember[]): void => {
      for (const member of members) {
        if (matchesTopic(member.iconicTaxon ?? undefined, [topic], member.scientificName)) take(member);
      }
    };
    topicFirst(recurrent.map(({ member }) => member));
    topicFirst(singleYear.map(({ member }) => member));
    topicFirst(historicalMembers);
    topicFirst(phenologyMembers);
  }

  // STRICT MODE (nc#233) STOPS HERE. `chosen` already holds every on-topic
  // member the four tiers could offer, in the resolver's own priority order —
  // that is exactly what the `topicFirst` pass above just built. The general
  // recipe's remaining steps exist only to backfill an unrelated cast up to
  // `MIN_MEMBERS`, which is precisely the mismatched fallback this mode must
  // never produce. Skipping them rather than filtering them is what makes
  // zero on-topic matches resolve to a genuinely empty cast instead of a
  // six-member one with one relevant face in it.
  if (query.topicFilter && topicMapped) {
    return {
      members: chosen.map((member, index) => ({ ...member, sortRank: index })),
      absences: buildAbsences(absent, windowDays, seen, admissible, topic),
    };
  }

  for (const { member } of recurrent) take(member);

  // Outside a mapped-topic lead, single-ping species only fill a short cast.
  // They keep the recorded tier because they genuinely were recorded; the
  // missing multi-year record remains explicit in yearsObserved.
  if (chosen.length < MIN_MEMBERS) {
    for (const { member } of singleYear) {
      if (chosen.length >= MIN_MEMBERS) break;
      take(member);
    }
  }

  // (4) In season. The regional tier fills a thin cast, and on day one in a
  // quiet recording area it IS the cast. Never merged into the recorded tier.
  if (chosen.length < MIN_MEMBERS) {
    // The observation record first. It is the same claim as the phenology
    // file's — "usually around here now" — asked of what people actually found
    // rather than of what somebody typed for a continent.
    for (const member of historicalMembers) {
      if (chosen.length >= MIN_MEMBERS) break;
      take(member);
    }
  }

  // Producer-curated expectations fill the regional tier. There is no local
  // calendar fallback if the producer supplied no validated entries.
  if (chosen.length < MIN_MEMBERS) {
    for (const member of phenologyMembers) {
      if (chosen.length >= MIN_MEMBERS) break;
      take(member);
    }
  }

  // (7) Striking absences: a strong multi-year record here that this read did
  // not return. Carried separately, never shown as something to find.
  return {
    members: chosen.map((member, index) => ({ ...member, sortRank: index })),
    absences: buildAbsences(absent, windowDays, seen, admissible, null),
  };
}

/**
 * Striking absences: a strong multi-year record here that this read did not
 * return. Shared by the general recipe and strict topic mode so the two never
 * apply different rules to the same list.
 *
 * `topic` is the strict-mode gate: null (the general path) carries every
 * qualifying absence exactly as this always has; a topic (strict path) keeps
 * only the ones taxonomy says belong to the lesson, for the same reason the
 * members list is filtered rather than ranked — a missing pear tree is not
 * evidence about a minibeast lesson either.
 */
function buildAbsences(
  absent: readonly RecurrenceEntry[],
  windowDays: number | null,
  seen: TaxonKeyring,
  admissible: (scientific: string | null) => boolean,
  topic: TopicTag | null
): ResolvedCastMember[] {
  const absences: ResolvedCastMember[] = [];
  const absenceSeen = new TaxonKeyring();
  for (const entry of absent) {
    if (absences.length >= MAX_ABSENCES) break;
    const member = toMember(entry, "recorded", windowDays, true);
    if (!member) continue;
    // Only a real record counts as a striking absence. Something that was
    // barely ever here is not missing, it is simply not here.
    if ((member.yearsObserved ?? 0) < RECURRENCE_YEARS) continue;
    if (!admissible(member.scientificName)) continue;
    if (topic !== null && !matchesTopic(member.iconicTaxon ?? undefined, [topic], member.scientificName)) continue;
    const row = { name: member.commonName, scientificName: member.scientificName };
    // A species cannot be both the thing to find and the thing that is missing.
    if (seen.has(row)) continue;
    if (!absenceSeen.claim(row)) continue;
    absences.push(member);
  }
  return absences.map((member, index) => ({ ...member, sortRank: index }));
}
