/**
 * The service-worker caching boundary, as a pure function the worker and its
 * verification share. Keeping the decision here — rather than only inside
 * app/sw.ts, which compiles to a webworker bundle a plain-node test can't load
 * — lets scripts/sw-cache-lint.mjs assert the exact boundary the worker ships
 * with, so "a personalised page is never persistently cached" is a red build,
 * not a manual promise.
 *
 * The rule (see app/sw.ts for the full reasoning):
 *   - /api/*        → never cached (live-only).
 *   - public routes → cacheable (rendered the same for everyone).
 *   - everything else that is a navigation → never persisted (personalised).
 */

/**
 * Exact pathnames safe to cache and serve offline: rendered identically for
 * every visitor, carrying no teacher, class, school, or child context. A new
 * route is private until it is proven public and added here on purpose.
 */
export const PUBLIC_ROUTES: ReadonlySet<string> = new Set([
  "/sign-in",
  // `/` and `/welcome` render the same public explanation, but their CTA is
  // teacher-aware. A cached signed-out copy would tell a returning teacher to
  // sign in again, so both landing addresses stay live-only (#871).
  // /read resolves the active class's place adaptation and nearby cast. It is
  // lesson-shaped, but it is not public and must never survive teacher signout.
  // "/session" left this list when lesson preparation began rendering the
  // signed-in teacher's class name and year group: a personalised page is
  // never persistently cached, and the sign-out sweep keeps PUBLIC_CACHE.
]);

/** Versioned name for the public-page cache. */
// v3 retires the former cacheable /welcome response. That response became
// teacher-aware in #871, so activation must delete v2 even on an upgrade where
// sign-out has never had a chance to sweep caches.
export const PUBLIC_CACHE = "nc-public-v3";

/** Data-free lesson shell used when a personalised navigation loses signal. */
export const OFFLINE_FALLBACK_ROUTE = "/field";
export const OFFLINE_PRINT_FALLBACK_ROUTE = "/field/print";

/**
 * Versioned name for the photograph cache (#375). A lesson's photo references
 * are fetched from the record's own hosts (iNaturalist, Wikimedia); a teacher
 * who opens the lesson on staffroom wifi and walks out to a field with no
 * signal would otherwise hold a row of broken image boxes exactly when she
 * wants to show the class a photograph. These images carry no teacher, class,
 * or child context — they are public observation photos — so caching them is
 * safe where caching a navigation is not, and they deliberately survive the
 * sign-out sweep.
 */
export const MEDIA_CACHE = "nc-media-v1";

/**
 * Whether a fetched resource belongs in the photograph cache: an https image
 * from another origin. Same-origin images ride the precache/build pipeline;
 * cross-origin non-images (scripts, frames) stay out on principle — this rule
 * exists for photographs, and a boundary that grows by accident is how the
 * blanket "pages" cache happened.
 */
export function isCacheableImageRequest(
  sameOrigin: boolean,
  destination: string,
  protocol: string
): boolean {
  return destination === "image" && !sameOrigin && protocol === "https:";
}

/**
 * Versioned name for the spoken-line recordings (nc#358).
 *
 * Same argument as MEDIA_CACHE, one step stronger. These mp3s are pack
 * content: the identical file is served to every teacher in every school, and
 * they carry no teacher, class, school or child context whatsoever — a
 * recording of an authored lesson line is exactly as public as the pack it
 * came from. So they are safe to keep on a shared iPad where a navigation is
 * not, and they deliberately survive the sign-out sweep.
 *
 * They are cached at RUNTIME rather than precached at install, and the
 * distinction is the whole reason this is a separate cache. The corpus is
 * megabytes; forcing all of it onto every device at install would spend a
 * school's storage on lessons it will never run. The runner fetches a
 * session's worth in the background the first time a teacher presses play,
 * which is the moment she has told us she wants it.
 */
export const AUDIO_CACHE = "nc-audio-v1";

/** Where the pre-generated spoken-line recordings are served from. */
export const AUDIO_PREFIX = "/lesson-audio/";

/**
 * Where the lesson preview's narrated cards are served from (nc#515).
 *
 * A SECOND PREFIX RATHER THAN A SUBFOLDER OF THE FIRST. They share this cache
 * — same argument, same lifetime, same survival of the sign-out sweep, because
 * both are pack content identical for every school. They do not share a
 * directory, because they are two corpora with two voices generated by two
 * scripts, and `synthesize-spoken-lines.mjs --prune` deletes any mp3 in its own
 * directory that its own corpus does not claim. Hiding one corpus inside the
 * other's folder would make that a landmine.
 */
export const PREVIEW_AUDIO_PREFIX = "/lesson-preview/";

/**
 * Whether a request is one of those recordings: same-origin, under one of the
 * audio prefixes. Same-origin is load-bearing — this rule exists for files this
 * app ships, and a boundary that grows by accident is how the blanket "pages"
 * cache happened.
 */
export function isSpokenAudioRequest(sameOrigin: boolean, pathname: string): boolean {
  return (
    sameOrigin &&
    (pathname.startsWith(AUDIO_PREFIX) || pathname.startsWith(PREVIEW_AUDIO_PREFIX)) &&
    pathname.endsWith(".mp3")
  );
}

/**
 * Versioned name for the lesson photography and illustrations (#1077).
 *
 * Same argument as AUDIO_CACHE, and it arrived the same way. These files are
 * pack content: the identical photograph is served to every teacher in every
 * school, and they carry no teacher, class, school or child context — a
 * picture of woodlice in a log is exactly as public as the lesson that shows
 * it. So they are safe to keep on a shared iPad where a navigation is not,
 * and they deliberately survive the sign-out sweep.
 *
 * They are cached at RUNTIME rather than precached at install, and that
 * distinction is the whole reason this cache exists. Precaching downloads
 * every lesson's photographs on install; the two folders reached 3.18 MB in
 * four days on ordinary content work, pushed onto every device the first time
 * it opened the app. The runner fetches a lesson's own pictures the first
 * time a teacher opens that lesson, which is the moment she has told us she
 * wants them.
 */
export const LESSON_IMAGE_CACHE = "nc-lesson-images-v1";

/**
 * Where those pictures are served from. Two prefixes rather than one folder,
 * for the same reason the audio corpora keep two: they are two bodies of work
 * with two provenances — photographs Johan supplied (`lesson-examples`) and
 * commissioned illustration (`lesson-illustrations`) — each with its own
 * README recording where it came from. They share a cache because they share
 * every property that decides caching, not because they are the same thing.
 */
export const LESSON_IMAGE_PREFIXES = [
  "/lesson-examples/",
  "/lesson-illustrations/",
] as const;

/**
 * Whether a request is one of those pictures: same-origin, under one of the
 * prefixes, and an image file. Same-origin is load-bearing — this rule exists
 * for files this app ships, and a boundary that grows by accident is how the
 * blanket "pages" cache happened. The extension check keeps the READMEs that
 * record each folder's provenance out of a cache meant for pictures.
 */
export function isLessonImageRequest(sameOrigin: boolean, pathname: string): boolean {
  if (!sameOrigin) return false;
  if (!LESSON_IMAGE_PREFIXES.some((prefix) => pathname.startsWith(prefix))) return false;
  return /\.(webp|png|jpe?g|svg|avif)$/i.test(pathname);
}

/** Message a signed-out client sends to have private caches swept. */
export const PURGE_PRIVATE_CACHES = "PURGE_PRIVATE_CACHES";

export type CacheDecision =
  /** API and personalised navigations: served live, never persisted. */
  | "network-only"
  /** Public, non-personalised pages: NetworkFirst into the public cache. */
  | "public-cache";

/**
 * Decide how a navigation to `pathname` is handled. Only navigations reach
 * this; asset and API routing is decided in the worker directly. A pathname
 * that is not on the public allowlist is personalised by default and is never
 * written to a persistent cache.
 */
export function cacheDecisionForNavigation(pathname: string): CacheDecision {
  return PUBLIC_ROUTES.has(pathname) ? "public-cache" : "network-only";
}
